name: Build

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint --errors-only $(git ls-files '*.py')

  build-for-linux:
    needs: quality-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk
          python -m pip install --upgrade pip
          pip install pyinstaller pillow numpy pygame colorlog requests

      - name: Prepare resources
        run: |
          mkdir -p dist_package

          pyinstaller --onefile --windowed --name "TrafficLightsCityLite" main.py
          cp dist/TrafficLightsCityLite* dist_package/

          cp -r assets/ dist_package/
          cp -r logs/ dist_package/
          cp -r saves/ dist_package/

      - name: Create zip archive
        run: |
          cd dist_package
          zip -r ../TrafficLightsCityLite-Linux.zip *
          cd ..

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            TrafficLightsCityLite-Linux.zip
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-for-windows:
    needs: quality-check
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow numpy pygame colorlog requests

      - name: Prepare resources
        run: |
          mkdir dist_package

          pyinstaller --onefile --windowed --name "TrafficLightsCityLite" main.py
          copy dist\TrafficLightsCityLite.exe dist_package\

          xcopy /E /I assets dist_package\assets
          xcopy /E /I logs dist_package\logs 
          xcopy /E /I saves dist_package\saves

      - name: Create zip archive
        run: |
          7z a -tzip TrafficLightsCityLite-Windows.zip .\dist_package\*

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            TrafficLightsCityLite-Windows.zip
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-for-macos:
    needs: quality-check
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow numpy pygame colorlog requests

      - name: Prepare resources
        run: |
          mkdir -p dist_package
          pyinstaller --windowed --name "TrafficLightsCityLite" main.py

          cp -R dist/TrafficLightsCityLite.app dist_package/

          cp -r assets/ dist_package/
          cp -r logs/ dist_package/
          cp -r saves/ dist_package/

      - name: Create zip archive
        run: |
          cd dist_package
          zip -r ../TrafficLightsCityLite-MacOS.zip *
          cd ..

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            TrafficLightsCityLite-MacOS.zip
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}