name: Build

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk
          python -m pip install --upgrade pip
          pip install pyinstaller pillow numpy pygame colorlog requests
      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --name "TrafficLightCity" main.py
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/TrafficLightCity*
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}