name: Build

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint --errors-only $(git ls-files '*.py')

  build:
    needs: quality-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk
          python -m pip install --upgrade pip
          pip install pyinstaller pillow numpy pygame colorlog requests

      - name: Prepare resources
        run: |
          mkdir -p dist_package

          pyinstaller --onefile --windowed --name "Lite" main.py
          cp dist/TrafficLightsCityLite* dist_package/

          cp -r assets/ dist_package/
          cp -r logs/ dist_package/
          cp -r saves/ dist_package/

      - name: Create zip archive
        run: |
          cd dist_package
          zip -r ../TrafficLightsCityLite.zip *
          cd ..

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            TrafficLightsCityLite.zip
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
